site_name: Hakaru
repo_url: https://github.com/hakaru-dev/hakaru
site_favicon: favicon.ico
site_author: Hakaru Team
extra_javascript:
    - 'js/mathjaxhelper.js'
    - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'


pages:
- Home: 'index.md'
- Introduction:
  - 'What is Probabilistic Programming?':          'intro/probprog.md'
  - 'Installing Hakaru':                           'intro/installation.md'
  - 'Generating Samples from your Hakaru Program': 'intro/samplegen.md'
  - 'Quick Start: A Mixture Model Example':        'intro/quickstart.md'
  - 'Examples':                                    'examples.md'
  - 'Compiling to Haskell':                        'transforms/compile.md' 
  - 'Compiling to C':                              'transforms/hkc.md' 
- Language Guide:
  - 'Primitive Probability Distributions': 'lang/rand.md'
  - 'Let and Bind':                        'lang/letbind.md'
  - 'Conditionals':                        'lang/cond.md'
  - 'Functions':                           'lang/functions.md'
  - 'Types and Coercions':                 'lang/coercions.md'
  - 'Data Types and Match':                'lang/datatypes.md'
  - 'Arrays and Plate':                    'lang/arrays.md'
  - 'Loops' :                              'lang/loops.md'
- Transformations:
  - 'Expect and Normalize': 'transforms/expect.md'
  - 'Disintegrate':         'transforms/disintegrate.md'
  - 'Density':              'transforms/density.md'
  - 'Simplify':             'transforms/simplify.md'
  - 'Metropolis Hastings':  'transforms/mh.md'
- Internals:
  - 'AST and Hakaru Datakind':   'internals/ast.md'
  - 'ABT':                       'internals/abt.md'
  - 'Datums':                    'internals/datums.md'
  - 'Coercions':                 'internals/coercions.md'
  - 'Transformaitons':           'internals/transforms.md'
  - 'Testing':                   'internals/testing.md'
  - 'Adding a Language Feature': 'internals/newfeature.md'
theme: yeti

markdown_extensions:
  - markdown.extensions.smarty
  - mdx_math
  - footnotes
