resolver: lts-7.12

# Local packages, usually specified by relative directory name
packages:
 - '.'
 - maple/

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
 - indentation-core-0.0
 - indentation-parsec-0.0
 - pretty-1.1.3.3
 - logfloat-0.13.3.3

 # Version Cabal-1.24.1.0 (which is in lts 7.12) seems to have impossible bound `base (>1 && <1),` ?? 
 # at least on hackage (https://hackage.haskell.org/package/Cabal-1.24.1.0)
 # Proper solution (?): lts-7.15 
 - Cabal-1.24.2.0

 # This pulls in about 5 additional transitive dependencies (building Cabal still takes 
 # about 80% of the compile time for the dependencies, total...)
 - tasty-hunit-adapter-1.1
 - tasty-hunit-0.9.2
 - tasty-0.11.0.4
 - tasty-rerun-1.1.6
 - tasty-html-0.4.1.1